/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  MarketDto
} from '.././model';

import { customInstance } from '.././axios';




/**
 * @summary Retrieves favorite markets for the user
 */
export const getFavoriteMarkets = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<MarketDto[]>(
      {url: `/favorites/markets`, method: 'GET', signal
    },
      );
    }
  

export const getGetFavoriteMarketsQueryKey = () => {
    return [`/favorites/markets`] as const;
    }

    
export const getGetFavoriteMarketsQueryOptions = <TData = Awaited<ReturnType<typeof getFavoriteMarkets>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteMarkets>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFavoriteMarketsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFavoriteMarkets>>> = ({ signal }) => getFavoriteMarkets(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFavoriteMarkets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFavoriteMarketsQueryResult = NonNullable<Awaited<ReturnType<typeof getFavoriteMarkets>>>
export type GetFavoriteMarketsQueryError = unknown


export function useGetFavoriteMarkets<TData = Awaited<ReturnType<typeof getFavoriteMarkets>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteMarkets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFavoriteMarkets>>,
          TError,
          Awaited<ReturnType<typeof getFavoriteMarkets>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFavoriteMarkets<TData = Awaited<ReturnType<typeof getFavoriteMarkets>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteMarkets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFavoriteMarkets>>,
          TError,
          Awaited<ReturnType<typeof getFavoriteMarkets>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFavoriteMarkets<TData = Awaited<ReturnType<typeof getFavoriteMarkets>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteMarkets>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves favorite markets for the user
 */

export function useGetFavoriteMarkets<TData = Awaited<ReturnType<typeof getFavoriteMarkets>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteMarkets>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFavoriteMarketsQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Favorites a market
 */
export const favoriteMarket = (
    marketId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/favorites/markets/${marketId}`, method: 'POST', signal
    },
      );
    }
  


export const getFavoriteMarketMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof favoriteMarket>>, TError,{marketId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof favoriteMarket>>, TError,{marketId: string}, TContext> => {

const mutationKey = ['favoriteMarket'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof favoriteMarket>>, {marketId: string}> = (props) => {
          const {marketId} = props ?? {};

          return  favoriteMarket(marketId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type FavoriteMarketMutationResult = NonNullable<Awaited<ReturnType<typeof favoriteMarket>>>
    
    export type FavoriteMarketMutationError = unknown

    /**
 * @summary Favorites a market
 */
export const useFavoriteMarket = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof favoriteMarket>>, TError,{marketId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof favoriteMarket>>,
        TError,
        {marketId: string},
        TContext
      > => {

      const mutationOptions = getFavoriteMarketMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Removes a market from the user's favorites
 */
export const unfavoriteMarket = (
    marketId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/favorites/markets/${marketId}`, method: 'DELETE'
    },
      );
    }
  


export const getUnfavoriteMarketMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unfavoriteMarket>>, TError,{marketId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof unfavoriteMarket>>, TError,{marketId: string}, TContext> => {

const mutationKey = ['unfavoriteMarket'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unfavoriteMarket>>, {marketId: string}> = (props) => {
          const {marketId} = props ?? {};

          return  unfavoriteMarket(marketId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UnfavoriteMarketMutationResult = NonNullable<Awaited<ReturnType<typeof unfavoriteMarket>>>
    
    export type UnfavoriteMarketMutationError = unknown

    /**
 * @summary Removes a market from the user's favorites
 */
export const useUnfavoriteMarket = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unfavoriteMarket>>, TError,{marketId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unfavoriteMarket>>,
        TError,
        {marketId: string},
        TContext
      > => {

      const mutationOptions = getUnfavoriteMarketMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    