/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import type { ProductDto } from './productDto';
import type { MarketDto } from './marketDto';

export interface PriceDto {
  /** Product's image URL */
  imageUrl: string;
  /** User unique identifier */
  userId: string;
  /** Update timestamp */
  updatedAt: string;
  /** Unique identifier of the price entry */
  id: string;
  /** Product price value */
  price: number;
  /** Indicates if the price was moderated (approved for public listing) */
  moderated: boolean;
  product: ProductDto;
  market: MarketDto;
}
