/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */

export interface ProductUpdateDto {
  /** Product's image URL */
  imageUrl?: string;
  /** Name of the product */
  name?: string;
  /** Detailed description of the product */
  description?: string;
  /** Category to which the product belongs */
  category?: string;
}
