/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */

export type ReadProductsParams = {
/**
 * Number of products to skip for pagination
 */
offset?: number;
/**
 * Maximum number of products to return
 */
limit?: number;
/**
 * Field to order the products by
 */
orderBy?: string;
/**
 * Search term to filter products by name or description
 */
search?: string;
};
