/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */

export type ReadPricesParams = {
/**
 * Offset for pagination
 */
offset?: number;
/**
 * Limit for pagination
 */
limit?: number;
/**
 * Field to order by
 */
orderBy?: string;
/**
 * Search term to filter results
 */
search?: string;
/**
 * Optional product ID to filter prices
 */
productId?: string;
/**
 * Optional market ID to filter prices
 */
marketId?: string;
};
