/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */

export interface ReportCreateDto {
  /** Unique identifier for the price entry */
  priceId: string;
  /** Reason for reporting a price */
  reason: string;
}
