/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ProductDto
} from '.././model';

import { customInstance } from '.././axios';




/**
 * @summary Retrieves favorite products for the user
 */
export const getFavoriteProducts = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<ProductDto[]>(
      {url: `/favorites/products`, method: 'GET', signal
    },
      );
    }
  

export const getGetFavoriteProductsQueryKey = () => {
    return [`/favorites/products`] as const;
    }

    
export const getGetFavoriteProductsQueryOptions = <TData = Awaited<ReturnType<typeof getFavoriteProducts>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteProducts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFavoriteProductsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFavoriteProducts>>> = ({ signal }) => getFavoriteProducts(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFavoriteProducts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFavoriteProductsQueryResult = NonNullable<Awaited<ReturnType<typeof getFavoriteProducts>>>
export type GetFavoriteProductsQueryError = unknown


export function useGetFavoriteProducts<TData = Awaited<ReturnType<typeof getFavoriteProducts>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteProducts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFavoriteProducts>>,
          TError,
          Awaited<ReturnType<typeof getFavoriteProducts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFavoriteProducts<TData = Awaited<ReturnType<typeof getFavoriteProducts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteProducts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFavoriteProducts>>,
          TError,
          Awaited<ReturnType<typeof getFavoriteProducts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFavoriteProducts<TData = Awaited<ReturnType<typeof getFavoriteProducts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteProducts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves favorite products for the user
 */

export function useGetFavoriteProducts<TData = Awaited<ReturnType<typeof getFavoriteProducts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteProducts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFavoriteProductsQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Favorites a product
 */
export const favoriteProduct = (
    productId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/favorites/products/${productId}`, method: 'POST', signal
    },
      );
    }
  


export const getFavoriteProductMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof favoriteProduct>>, TError,{productId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof favoriteProduct>>, TError,{productId: string}, TContext> => {

const mutationKey = ['favoriteProduct'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof favoriteProduct>>, {productId: string}> = (props) => {
          const {productId} = props ?? {};

          return  favoriteProduct(productId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type FavoriteProductMutationResult = NonNullable<Awaited<ReturnType<typeof favoriteProduct>>>
    
    export type FavoriteProductMutationError = unknown

    /**
 * @summary Favorites a product
 */
export const useFavoriteProduct = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof favoriteProduct>>, TError,{productId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof favoriteProduct>>,
        TError,
        {productId: string},
        TContext
      > => {

      const mutationOptions = getFavoriteProductMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Removes a product from the user's favorites
 */
export const unfavoriteProduct = (
    productId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/favorites/products/${productId}`, method: 'DELETE'
    },
      );
    }
  


export const getUnfavoriteProductMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unfavoriteProduct>>, TError,{productId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof unfavoriteProduct>>, TError,{productId: string}, TContext> => {

const mutationKey = ['unfavoriteProduct'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unfavoriteProduct>>, {productId: string}> = (props) => {
          const {productId} = props ?? {};

          return  unfavoriteProduct(productId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UnfavoriteProductMutationResult = NonNullable<Awaited<ReturnType<typeof unfavoriteProduct>>>
    
    export type UnfavoriteProductMutationError = unknown

    /**
 * @summary Removes a product from the user's favorites
 */
export const useUnfavoriteProduct = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unfavoriteProduct>>, TError,{productId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unfavoriteProduct>>,
        TError,
        {productId: string},
        TContext
      > => {

      const mutationOptions = getUnfavoriteProductMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    