/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';

import type {
  ProductDto
} from '.././model';


export const getGetFavoriteProductsResponseMock = (): ProductDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, imageUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), id: faker.string.alpha(20), name: faker.string.alpha(20), description: faker.string.alpha(20), category: faker.string.alpha(20), lowestPrice: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined])})))


export const getGetFavoriteProductsMockHandler = (overrideResponse?: ProductDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ProductDto[]> | ProductDto[])) => {
  return http.get('*/favorites/products', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetFavoriteProductsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getFavoriteProductMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void)) => {
  return http.post('*/favorites/products/:productId', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 204,
        
      })
  })
}

export const getUnfavoriteProductMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void)) => {
  return http.delete('*/favorites/products/:productId', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 204,
        
      })
  })
}
export const getFavoriteProductMock = () => [
  getGetFavoriteProductsMockHandler(),
  getFavoriteProductMockHandler(),
  getUnfavoriteProductMockHandler()
]
