/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ProductCreateDto,
  ProductDto,
  ProductUpdateDto,
  ProductsDto,
  ProductsMergeDto,
  ReadProductsParams
} from '.././model';

import { customInstance } from '.././axios';




/**
 * @summary Creates a new product.
 */
export const createProduct = (
    productCreateDto: ProductCreateDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ProductDto>(
      {url: `/products`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: productCreateDto, signal
    },
      );
    }
  


export const getCreateProductMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProduct>>, TError,{data: ProductCreateDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createProduct>>, TError,{data: ProductCreateDto}, TContext> => {

const mutationKey = ['createProduct'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProduct>>, {data: ProductCreateDto}> = (props) => {
          const {data} = props ?? {};

          return  createProduct(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProductMutationResult = NonNullable<Awaited<ReturnType<typeof createProduct>>>
    export type CreateProductMutationBody = ProductCreateDto
    export type CreateProductMutationError = unknown

    /**
 * @summary Creates a new product.
 */
export const useCreateProduct = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProduct>>, TError,{data: ProductCreateDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProduct>>,
        TError,
        {data: ProductCreateDto},
        TContext
      > => {

      const mutationOptions = getCreateProductMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Retrieves a list of products.
 */
export const readProducts = (
    params?: ReadProductsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ProductsDto>(
      {url: `/products`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getReadProductsQueryKey = (params?: ReadProductsParams,) => {
    return [`/products`, ...(params ? [params]: [])] as const;
    }

    
export const getReadProductsQueryOptions = <TData = Awaited<ReturnType<typeof readProducts>>, TError = unknown>(params?: ReadProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProducts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadProductsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof readProducts>>> = ({ signal }) => readProducts(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readProducts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadProductsQueryResult = NonNullable<Awaited<ReturnType<typeof readProducts>>>
export type ReadProductsQueryError = unknown


export function useReadProducts<TData = Awaited<ReturnType<typeof readProducts>>, TError = unknown>(
 params: undefined |  ReadProductsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProducts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readProducts>>,
          TError,
          Awaited<ReturnType<typeof readProducts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadProducts<TData = Awaited<ReturnType<typeof readProducts>>, TError = unknown>(
 params?: ReadProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProducts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readProducts>>,
          TError,
          Awaited<ReturnType<typeof readProducts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadProducts<TData = Awaited<ReturnType<typeof readProducts>>, TError = unknown>(
 params?: ReadProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProducts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves a list of products.
 */

export function useReadProducts<TData = Awaited<ReturnType<typeof readProducts>>, TError = unknown>(
 params?: ReadProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProducts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadProductsQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Retrieves a product by its ID.
 */
export const readProduct = (
    productId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ProductDto>(
      {url: `/products/${productId}`, method: 'GET', signal
    },
      );
    }
  

export const getReadProductQueryKey = (productId: string,) => {
    return [`/products/${productId}`] as const;
    }

    
export const getReadProductQueryOptions = <TData = Awaited<ReturnType<typeof readProduct>>, TError = unknown>(productId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProduct>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadProductQueryKey(productId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof readProduct>>> = ({ signal }) => readProduct(productId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(productId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readProduct>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadProductQueryResult = NonNullable<Awaited<ReturnType<typeof readProduct>>>
export type ReadProductQueryError = unknown


export function useReadProduct<TData = Awaited<ReturnType<typeof readProduct>>, TError = unknown>(
 productId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProduct>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readProduct>>,
          TError,
          Awaited<ReturnType<typeof readProduct>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadProduct<TData = Awaited<ReturnType<typeof readProduct>>, TError = unknown>(
 productId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProduct>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readProduct>>,
          TError,
          Awaited<ReturnType<typeof readProduct>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadProduct<TData = Awaited<ReturnType<typeof readProduct>>, TError = unknown>(
 productId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProduct>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves a product by its ID.
 */

export function useReadProduct<TData = Awaited<ReturnType<typeof readProduct>>, TError = unknown>(
 productId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProduct>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadProductQueryOptions(productId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Updates a product by its ID.
 */
export const updateProduct = (
    productId: string,
    productUpdateDto: ProductUpdateDto,
 ) => {
      
      
      return customInstance<ProductDto>(
      {url: `/products/${productId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: productUpdateDto
    },
      );
    }
  


export const getUpdateProductMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProduct>>, TError,{productId: string;data: ProductUpdateDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateProduct>>, TError,{productId: string;data: ProductUpdateDto}, TContext> => {

const mutationKey = ['updateProduct'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProduct>>, {productId: string;data: ProductUpdateDto}> = (props) => {
          const {productId,data} = props ?? {};

          return  updateProduct(productId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateProductMutationResult = NonNullable<Awaited<ReturnType<typeof updateProduct>>>
    export type UpdateProductMutationBody = ProductUpdateDto
    export type UpdateProductMutationError = unknown

    /**
 * @summary Updates a product by its ID.
 */
export const useUpdateProduct = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProduct>>, TError,{productId: string;data: ProductUpdateDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProduct>>,
        TError,
        {productId: string;data: ProductUpdateDto},
        TContext
      > => {

      const mutationOptions = getUpdateProductMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Deletes a product by its ID.
 */
export const deleteProduct = (
    productId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/products/${productId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteProductMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProduct>>, TError,{productId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteProduct>>, TError,{productId: string}, TContext> => {

const mutationKey = ['deleteProduct'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProduct>>, {productId: string}> = (props) => {
          const {productId} = props ?? {};

          return  deleteProduct(productId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteProductMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProduct>>>
    
    export type DeleteProductMutationError = unknown

    /**
 * @summary Deletes a product by its ID.
 */
export const useDeleteProduct = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProduct>>, TError,{productId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProduct>>,
        TError,
        {productId: string},
        TContext
      > => {

      const mutationOptions = getDeleteProductMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Merge duplicate products into a target product
 */
export const mergeProducts = (
    productsMergeDto: ProductsMergeDto,
 ) => {
      
      
      return customInstance<void>(
      {url: `/products/merge`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: productsMergeDto
    },
      );
    }
  


export const getMergeProductsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mergeProducts>>, TError,{data: ProductsMergeDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof mergeProducts>>, TError,{data: ProductsMergeDto}, TContext> => {

const mutationKey = ['mergeProducts'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof mergeProducts>>, {data: ProductsMergeDto}> = (props) => {
          const {data} = props ?? {};

          return  mergeProducts(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MergeProductsMutationResult = NonNullable<Awaited<ReturnType<typeof mergeProducts>>>
    export type MergeProductsMutationBody = ProductsMergeDto
    export type MergeProductsMutationError = unknown

    /**
 * @summary Merge duplicate products into a target product
 */
export const useMergeProducts = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mergeProducts>>, TError,{data: ProductsMergeDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof mergeProducts>>,
        TError,
        {data: ProductsMergeDto},
        TContext
      > => {

      const mutationOptions = getMergeProductsMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    