/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';

import type {
  PriceDto,
  PricesDto
} from '.././model';


export const getCreatePriceResponseMock = (overrideResponse: Partial< PriceDto > = {}): PriceDto => ({imageUrl: faker.string.alpha(20), userId: faker.string.alpha(20), updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, id: faker.string.alpha(20), price: faker.number.int({min: undefined, max: undefined}), moderated: faker.datatype.boolean(), product: {updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, imageUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), id: faker.string.alpha(20), name: faker.string.alpha(20), description: faker.string.alpha(20), category: faker.string.alpha(20), lowestPrice: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined])}, market: {updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, imageUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), id: faker.string.alpha(20), name: faker.string.alpha(20), address: faker.string.alpha(20), city: faker.string.alpha(20), state: faker.string.alpha(20)}, ...overrideResponse})

export const getReadPricesResponseMock = (overrideResponse: Partial< PricesDto > = {}): PricesDto => ({records: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({imageUrl: faker.string.alpha(20), userId: faker.string.alpha(20), updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, id: faker.string.alpha(20), price: faker.number.int({min: undefined, max: undefined}), moderated: faker.datatype.boolean(), product: {updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, imageUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), id: faker.string.alpha(20), name: faker.string.alpha(20), description: faker.string.alpha(20), category: faker.string.alpha(20), lowestPrice: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined])}, market: {updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, imageUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), id: faker.string.alpha(20), name: faker.string.alpha(20), address: faker.string.alpha(20), city: faker.string.alpha(20), state: faker.string.alpha(20)}})), count: faker.number.int({min: undefined, max: undefined}), total: faker.number.int({min: undefined, max: undefined}), nextOffset: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), null]), undefined]), ...overrideResponse})


export const getCreatePriceMockHandler = (overrideResponse?: PriceDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PriceDto> | PriceDto)) => {
  return http.post('*/prices', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getCreatePriceResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getReadPricesMockHandler = (overrideResponse?: PricesDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PricesDto> | PricesDto)) => {
  return http.get('*/prices', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getReadPricesResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}
export const getPriceMock = () => [
  getCreatePriceMockHandler(),
  getReadPricesMockHandler()
]
