import { appColors } from "@/constants/theme";
import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FAFAFA",
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: 20,
    paddingTop: 10,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 24,
    color: appColors.primary,
    textAlign: "center",
  },
  formGroup: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 15,
    marginBottom: 8,
    color: "#555",
    fontWeight: "500",
  },
  input: {
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
    fontSize: 16,
    backgroundColor: "#FFF",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  inputFocused: {
    borderColor: appColors.primary,
    borderWidth: 1.5,
  },
  inputError: {
    borderColor: "#FF5252",
    backgroundColor: "#FFF8F8",
  },
  errorText: {
    color: "#FF5252",
    fontSize: 13,
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  imageSection: {
    marginBottom: 24,
  },
  imageLabel: {
    fontSize: 15,
    marginBottom: 8,
    color: "#555",
    fontWeight: "500",
  },
  imageContainer: {
    width: "100%",
    height: 220,
    backgroundColor: "#f9f9f9",
    borderRadius: 12,
    marginBottom: 8,

    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderStyle: "dashed",
  },
  image: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  imagePlaceholder: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  placeholderText: {
    color: "#9E9E9E",
    fontSize: 15,
    textAlign: "center",
    marginTop: 8,
    paddingHorizontal: 20,
  },
  placeholderIcon: {
    marginBottom: 8,
  },
  imageInfo: {
    fontSize: 13,
    color: "#757575",
    textAlign: "center",
  },
  barcodeSection: {
    marginBottom: 20,
  },
  barcodeContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  barcodeInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 12,
    padding: 14,
    fontSize: 16,
    backgroundColor: "#FFF",
  },
  scanButton: {
    backgroundColor: "#F5F5F5",
    width: 50,
    height: 50,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  buttonGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: -5,
    marginBottom: 16,
  },
  buttonItem: {
    width: (width - 50) / 2,
    margin: 5,
  },
  button: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F5F5F5",
    padding: 14,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  primaryButton: {
    backgroundColor: appColors.primary,
  },
  buttonText: {
    marginLeft: 8,
    fontSize: 15,
    color: "#555",
    fontWeight: "500",
  },
  primaryButtonText: {
    color: "#FFF",
    fontWeight: "bold",
  },
  divider: {
    height: 1,
    backgroundColor: "#EEEEEE",
    marginVertical: 20,
  },
  saveButtonContainer: {
    marginTop: 30,
    marginBottom: 40,
  },
  saveButton: {
    backgroundColor: appColors.primary,
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  saveButtonText: {
    color: "#FFF",
    fontSize: 17,
    fontWeight: "bold",
  },
  textArea: {
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 12,
    padding: 14,
    fontSize: 16,
    marginBottom: 8,
    backgroundColor: "#FFF",
    height: 100,
    textAlignVertical: "top",
  },
  priceContainer: {
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 12,
    backgroundColor: "#FFF",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  priceCurrency: {
    fontSize: 16,
    color: "#555",
    paddingLeft: 14,
  },
  priceInput: {
    flex: 1,
    padding: 14,
    fontSize: 16,
  },
  categoryTag: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F0F8FF",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#E1EFFF",
  },
  categoryText: {
    color: appColors.primary,
    fontSize: 14,
    marginRight: 4,
  },
  categoryIcon: {
    color: appColors.primary,
  },
  categoryContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 8,
  },
  stepperHeader: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 20,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderColor: "#EEEEEE",
  },
  stepContainer: {
    flex: 1,
    alignItems: "center",
    maxWidth: 120,
  },
  stepActive: {
    opacity: 1,
  },
  stepCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#F0F0F0",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 4,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  stepCircleActive: {
    backgroundColor: appColors.primary,
    borderColor: appColors.primary,
  },
  stepCircleCompleted: {
    backgroundColor: appColors.primary,
    borderColor: appColors.primary,
  },
  stepNumber: {
    fontSize: 14,
    color: "#777777",
    fontWeight: "bold",
  },
  stepNumberActive: {
    color: "#FFFFFF",
  },
  stepText: {
    fontSize: 12,
    color: "#777777",
    textAlign: "center",
  },
  stepTextActive: {
    color: appColors.primary,
    fontWeight: "500",
  },
  stepperLine: {
    flex: 1,
    height: 2,
    backgroundColor: "#E0E0E0",
    marginHorizontal: 8,
    maxWidth: 80,
  },
  // Step Content styles
  stepContent: {
    paddingVertical: 20,
  },
  stepTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 20,
    color: appColors.primary,
    textAlign: "center",
  },
  // Product selection styles
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    marginBottom: 24,
    paddingRight: 10,
  },
  searchInput: {
    flex: 1,
    height: 50,
    paddingHorizontal: 16,
    fontSize: 16,
  },
  searchIcon: {
    marginHorizontal: 8,
  },
  productsList: {
    maxHeight: 300,
    marginBottom: 16,
  },
  productItem: {
    backgroundColor: "#FFF",
    padding: 16,
    borderRadius: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  productItemName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
    marginBottom: 4,
  },
  productItemCategory: {
    fontSize: 14,
    color: "#777",
  },
  loadingContainer: {
    alignItems: "center",
    justifyContent: "center",
    padding: 40,
  },
  loadingText: {
    marginTop: 16,
    color: "#777",
    fontSize: 16,
  },
  noResultsContainer: {
    alignItems: "center",
    padding: 40,
  },
  noResultsText: {
    color: "#777",
    fontSize: 16,
    marginBottom: 20,
    textAlign: "center",
  },
  createNewButton: {
    backgroundColor: appColors.primary,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    marginTop: 16,
    marginBottom: 16,
    alignSelf: "center",
  },
  createNewButtonText: {
    color: "#FFF",
    fontWeight: "bold",
    fontSize: 15,
  },
  initialSelectionContainer: {
    alignItems: "center",
    padding: 40,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 12,
    borderStyle: "dashed",
    backgroundColor: "#FAFAFA",
  },
  initialSelectionText: {
    color: "#777",
    fontSize: 16,
    marginBottom: 10,
    textAlign: "center",
  },
  // Navigation buttons
  buttonsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 30,
    marginBottom: 30,
    paddingHorizontal: 10,
  },
  backButton: {
    flex: 1,
    backgroundColor: "#F5F5F5",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    marginRight: 10,
  },
  backButtonText: {
    color: "#555",
    fontSize: 16,
    fontWeight: "600",
  },
  nextButton: {
    flex: 2,
    backgroundColor: appColors.primary,
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  nextButtonText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  // For existing products where fields should be read-only
  disabledInput: {
    backgroundColor: "#F5F5F5",
    opacity: 0.8,
  },

  // Market styles
  marketItem: {
    backgroundColor: "#FFF",
    padding: 16,
    borderRadius: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  marketItemName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
    marginBottom: 4,
  },
  marketItemAddress: {
    fontSize: 14,
    color: "#777",
    marginBottom: 2,
  },
  marketItemLocation: {
    fontSize: 12,
    color: "#999",
  },
  marketsList: {
    maxHeight: 300,
    marginBottom: 16,
  },
  marketsScrollView: {
    maxHeight: 300,
    marginBottom: 16,
  },
  rowContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  selectedMarketContainer: {
    backgroundColor: "#F9F9F9",
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  selectedMarketTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#555",
    marginBottom: 10,
  },
  selectedMarket: {
    backgroundColor: "#FFF",
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    position: "relative",
    paddingRight: 80,
    flexDirection: "row",
    alignItems: "center",
  },
  selectedMarketImage: {
    width: 50,
    height: 50,
    borderRadius: 8,
    marginRight: 12,
    backgroundColor: "#F5F5F5",
  },
  selectedMarketInfo: {
    flex: 1,
    marginRight: 10,
  },
  selectedMarketName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
    marginBottom: 4,
  },
  selectedMarketAddress: {
    fontSize: 14,
    color: "#777",
    marginBottom: 2,
  },
  selectedMarketLocation: {
    fontSize: 12,
    color: "#999",
  },
  changeMarketButton: {
    position: "absolute",
    right: 16,
    top: "50%",
    marginTop: -18,
    backgroundColor: "#F0F0F0",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  changeMarketButtonText: {
    fontSize: 14,
    color: "#555",
    fontWeight: "500",
  },

  // Selected product styles (for market selection step)
  selectedProductContainer: {
    backgroundColor: "#F9F9F9",
    borderRadius: 12,
    padding: 16,
    marginTop: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  selectedProductTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#555",
    marginBottom: 10,
  },
  selectedProduct: {
    backgroundColor: "#FFF",
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    position: "relative",
    paddingRight: 80,
    flexDirection: "row",
    alignItems: "center",
  },
  selectedProductImage: {
    width: 50,
    height: 50,
    borderRadius: 8,
    marginRight: 12,
    backgroundColor: "#F5F5F5",
  },
  selectedProductInfo: {
    flex: 1,
    marginRight: 10,
  },
  selectedProductName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
    marginBottom: 4,
  },
  selectedProductCategory: {
    fontSize: 14,
    color: "#777",
  },
  changeProductButton: {
    position: "absolute",
    right: 16,
    top: "50%",
    marginTop: -18,
    backgroundColor: "#F0F0F0",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  changeProductButtonText: {
    fontSize: 14,
    color: "#555",
    fontWeight: "500",
  },

  // Summary styles for Price Details step
  summaryContainer: {
    backgroundColor: "#F9F9F9",
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  summaryTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#555",
    marginBottom: 16,
    textAlign: "center",
  },
  summarySection: {
    flexDirection: "row",
    marginBottom: 8,
    alignItems: "flex-start",
  },
  summaryLabel: {
    fontSize: 14,
    color: "#666",
    fontWeight: "500",
    width: 85,
  },
  summaryValue: {
    fontSize: 14,
    color: "#333",
    flex: 1,
  },
  summaryProductSection: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  summaryProductImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginRight: 12,
    backgroundColor: "#F5F5F5",
  },
  summaryProductInfo: {
    flex: 1,
  },
  summaryMarketSection: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  summaryMarketImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginRight: 12,
    backgroundColor: "#F5F5F5",
  },
  summaryMarketInfo: {
    flex: 1,
  },
  // Action buttons for ProductSelectionStep
  actionButtonsContainer: {
    marginTop: 16,
    marginBottom: 16,
    width: "100%",
    gap: 10,
  },
  scannerButton: {
    backgroundColor: "#4B7BEC",
    marginTop: 10,
  },
  scannerButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
});
