export enum MainTag {
  MAIN = 'MAIN',
  CLERK = 'CLERK',
  UPLOAD = 'UPLOAD',
  SUPABASE = 'SUPABASE',
  EXCEPTION = 'EXCEPTION',
  HTTP = 'HTTP',
  PRICE_LISTENER = 'PRICE_LISTENER',
  PRICE_COMPARATOR = 'PRICE_COMPARATOR',
  NOTIFICATION = 'NOTIFICATION',
  EXPO_PUSH_NOTIFICATION = 'EXPO_PUSH_NOTIFICATION',
  DISCORD_NOTIFICATION = 'DISCORD_NOTIFICATION',
  SENDGRID_NOTIFICATION = 'SENDGRID_NOTIFICATION',
}