/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  UploadControllerUploadImageBody,
  UploadImageDto
} from '.././model';

import { customInstance } from '.././axios';




/**
 * @summary Uploads an image and returns the public URL
 */
export const uploadControllerUploadImage = (
    uploadControllerUploadImageBody: UploadControllerUploadImageBody,
 signal?: AbortSignal
) => {
      
      const formData = new FormData();
if(uploadControllerUploadImageBody.file !== undefined) {
 formData.append(`file`, uploadControllerUploadImageBody.file)
 }

      return customInstance<UploadImageDto>(
      {url: `/upload/image`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      );
    }
  


export const getUploadControllerUploadImageMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadControllerUploadImage>>, TError,{data: UploadControllerUploadImageBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof uploadControllerUploadImage>>, TError,{data: UploadControllerUploadImageBody}, TContext> => {

const mutationKey = ['uploadControllerUploadImage'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadControllerUploadImage>>, {data: UploadControllerUploadImageBody}> = (props) => {
          const {data} = props ?? {};

          return  uploadControllerUploadImage(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadControllerUploadImageMutationResult = NonNullable<Awaited<ReturnType<typeof uploadControllerUploadImage>>>
    export type UploadControllerUploadImageMutationBody = UploadControllerUploadImageBody
    export type UploadControllerUploadImageMutationError = unknown

    /**
 * @summary Uploads an image and returns the public URL
 */
export const useUploadControllerUploadImage = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadControllerUploadImage>>, TError,{data: UploadControllerUploadImageBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadControllerUploadImage>>,
        TError,
        {data: UploadControllerUploadImageBody},
        TContext
      > => {

      const mutationOptions = getUploadControllerUploadImageMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    