/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';

import type {
  UploadImageDto
} from '.././model';


export const getUploadControllerUploadImageResponseMock = (overrideResponse: Partial< UploadImageDto > = {}): UploadImageDto => ({imageUrl: faker.string.alpha(20), ...overrideResponse})


export const getUploadControllerUploadImageMockHandler = (overrideResponse?: UploadImageDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<UploadImageDto> | UploadImageDto)) => {
  return http.post('*/upload/image', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUploadControllerUploadImageResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}
export const getUploadMock = () => [
  getUploadControllerUploadImageMockHandler()
]
