/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';

import type {
  ReportDto,
  ReportsDto
} from '.././model';


export const getCreateReportResponseMock = (overrideResponse: Partial< ReportDto > = {}): ReportDto => ({userId: faker.string.alpha(20), updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, id: faker.string.alpha(20), reason: faker.string.alpha(20), resolved: faker.datatype.boolean(), price: {...{imageUrl: faker.string.alpha(20), userId: faker.string.alpha(20), updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, id: faker.string.alpha(20), price: faker.number.int({min: undefined, max: undefined}), moderated: faker.datatype.boolean(), product: {updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, imageUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), id: faker.string.alpha(20), name: faker.string.alpha(20), description: faker.string.alpha(20), category: faker.string.alpha(20), lowestPrice: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined])}, market: {updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, imageUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), id: faker.string.alpha(20), name: faker.string.alpha(20), address: faker.string.alpha(20), city: faker.string.alpha(20), state: faker.string.alpha(20)}},}, status: faker.helpers.arrayElement([faker.helpers.arrayElement(['APPROVED','REJECTED'] as const), undefined]), ...overrideResponse})

export const getReadReportsResponseMock = (overrideResponse: Partial< ReportsDto > = {}): ReportsDto => ({records: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({userId: faker.string.alpha(20), updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, id: faker.string.alpha(20), reason: faker.string.alpha(20), resolved: faker.datatype.boolean(), price: {...{imageUrl: faker.string.alpha(20), userId: faker.string.alpha(20), updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, id: faker.string.alpha(20), price: faker.number.int({min: undefined, max: undefined}), moderated: faker.datatype.boolean(), product: {updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, imageUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), id: faker.string.alpha(20), name: faker.string.alpha(20), description: faker.string.alpha(20), category: faker.string.alpha(20), lowestPrice: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined])}, market: {updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, imageUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), id: faker.string.alpha(20), name: faker.string.alpha(20), address: faker.string.alpha(20), city: faker.string.alpha(20), state: faker.string.alpha(20)}},}, status: faker.helpers.arrayElement([faker.helpers.arrayElement(['APPROVED','REJECTED'] as const), undefined])})), count: faker.number.int({min: undefined, max: undefined}), total: faker.number.int({min: undefined, max: undefined}), nextOffset: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), null]), undefined]), ...overrideResponse})

export const getUpdateReportResponseMock = (overrideResponse: Partial< ReportDto > = {}): ReportDto => ({userId: faker.string.alpha(20), updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, id: faker.string.alpha(20), reason: faker.string.alpha(20), resolved: faker.datatype.boolean(), price: {...{imageUrl: faker.string.alpha(20), userId: faker.string.alpha(20), updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, id: faker.string.alpha(20), price: faker.number.int({min: undefined, max: undefined}), moderated: faker.datatype.boolean(), product: {updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, imageUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), id: faker.string.alpha(20), name: faker.string.alpha(20), description: faker.string.alpha(20), category: faker.string.alpha(20), lowestPrice: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined])}, market: {updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, imageUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), id: faker.string.alpha(20), name: faker.string.alpha(20), address: faker.string.alpha(20), city: faker.string.alpha(20), state: faker.string.alpha(20)}},}, status: faker.helpers.arrayElement([faker.helpers.arrayElement(['APPROVED','REJECTED'] as const), undefined]), ...overrideResponse})


export const getCreateReportMockHandler = (overrideResponse?: ReportDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ReportDto> | ReportDto)) => {
  return http.post('*/reports', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getCreateReportResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getReadReportsMockHandler = (overrideResponse?: ReportsDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ReportsDto> | ReportsDto)) => {
  return http.get('*/reports', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getReadReportsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getUpdateReportMockHandler = (overrideResponse?: ReportDto | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<ReportDto> | ReportDto)) => {
  return http.patch('*/reports/:reportId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUpdateReportResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}
export const getReportMock = () => [
  getCreateReportMockHandler(),
  getReadReportsMockHandler(),
  getUpdateReportMockHandler()
]
