/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */

export interface MarketUpdateDto {
  /** Product's image URL */
  imageUrl?: string;
  /** Name of the market */
  name?: string;
  /** Street address of the market */
  address?: string;
  /** City where the market is located */
  city?: string;
  /** State where the market is located */
  state?: string;
}
