/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */

export interface PriceCreateDto {
  /** Unique identifier for the product */
  productId: string;
  /** Unique identifier for the market */
  marketId: string;
  /** Product's image URL */
  imageUrl: string;
  /** Product price value */
  price: number;
}
