/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */

export interface ProductsMergeDto {
  /** ID of the product that will be kept (target) */
  targetProductId: string;
  /** List of duplicate product IDs to merge into the target */
  productIds: string[];
}
