/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */

export type ReadMarketsParams = {
/**
 * Number of markets to skip for pagination
 */
offset?: number;
/**
 * Maximum number of markets to return
 */
limit?: number;
/**
 * Field to order the markets by
 */
orderBy?: string;
/**
 * Search term to filter markets by name or address
 */
search?: string;
};
