/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */

/**
 * Current status of the report
 */
export type ReportUpdateDtoStatus = typeof ReportUpdateDtoStatus[keyof typeof ReportUpdateDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReportUpdateDtoStatus = {
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;
