/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import type { PriceDto } from './priceDto';
import type { ReportDtoStatus } from './reportDtoStatus';

export interface ReportDto {
  /** User unique identifier */
  userId: string;
  /** Update timestamp */
  updatedAt: string;
  /** Unique identifier of the report */
  id: string;
  /** Reason for reporting a price */
  reason: string;
  /** Indicates whether the report has been resolved */
  resolved: boolean;
  /** Information about the price associated with the report */
  price: PriceDto;
  /** Current status of the report */
  status?: ReportDtoStatus;
}
