/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import type { ReportUpdateDtoStatus } from './reportUpdateDtoStatus';

export interface ReportUpdateDto {
  /** Indicates whether the report has been resolved */
  resolved: boolean;
  /** Current status of the report */
  status?: ReportUpdateDtoStatus;
}
