/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';

import type {
  MarketDto
} from '.././model';


export const getGetFavoriteMarketsResponseMock = (): MarketDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, imageUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), id: faker.string.alpha(20), name: faker.string.alpha(20), address: faker.string.alpha(20), city: faker.string.alpha(20), state: faker.string.alpha(20)})))


export const getGetFavoriteMarketsMockHandler = (overrideResponse?: MarketDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MarketDto[]> | MarketDto[])) => {
  return http.get('*/favorites/markets', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetFavoriteMarketsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getFavoriteMarketMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void)) => {
  return http.post('*/favorites/markets/:marketId', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 204,
        
      })
  })
}

export const getUnfavoriteMarketMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void)) => {
  return http.delete('*/favorites/markets/:marketId', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 204,
        
      })
  })
}
export const getFavoriteMarketMock = () => [
  getGetFavoriteMarketsMockHandler(),
  getFavoriteMarketMockHandler(),
  getUnfavoriteMarketMockHandler()
]
