import { appColors } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const benefitsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: appColors.background,
  },
  header: {
    backgroundColor: appColors.surface,
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: appColors.disabled + "40",
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: appColors.primary,
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 14,
    color: appColors.placeholder,
  },
  listContainer: {
    padding: 16,
  },
  benefitCard: {
    backgroundColor: appColors.surface,
    borderRadius: 12,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    overflow: "hidden",
  },
  benefitImage: {
    width: "100%",
    height: 120,
    resizeMode: "cover",
  },
  benefitContent: {
    padding: 16,
  },
  benefitName: {
    fontSize: 18,
    fontWeight: "600",
    color: appColors.text,
    marginBottom: 4,
  },
  benefitType: {
    fontSize: 12,
    fontWeight: "500",
    color: appColors.primary,
    backgroundColor: appColors.primary + "20",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: "flex-start",
    marginBottom: 8,
    textTransform: "uppercase",
  },
  benefitDescription: {
    fontSize: 14,
    color: appColors.placeholder,
    lineHeight: 20,
    marginBottom: 12,
  },
  benefitDates: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  dateText: {
    fontSize: 12,
    color: appColors.disabled,
    flex: 1,
  },
  statusContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
    paddingVertical: 4,
  },
  statusText: {
    fontSize: 12,
    fontWeight: "600",
    textTransform: "uppercase",
  },
  codeContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: appColors.primary + "20",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  codeText: {
    fontSize: 12,
    fontWeight: "600",
    color: appColors.primary,
    marginRight: 4,
  },
  copyIcon: {
    fontSize: 12,
  },
  benefitTimestamps: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: appColors.disabled + "30",
  },
  timestampText: {
    paddingVertical: 2,
    fontSize: 11,
    color: appColors.disabled,
    marginBottom: 2,
  },
  actionContainer: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: appColors.disabled + "20",
  },
  actionButton: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
  },
  claimButton: {
    backgroundColor: appColors.primary,
  },
  claimButtonText: {
    color: appColors.surface,
    fontSize: 16,
    fontWeight: "600",
  },
  claimedButton: {
    backgroundColor: appColors.secondary + "20",
    borderWidth: 1,
    borderColor: appColors.secondary,
  },
  claimedButtonText: {
    color: appColors.secondary,
    fontSize: 14,
    fontWeight: "600",
  },
  consumedButton: {
    backgroundColor: appColors.disabled + "20",
    borderWidth: 1,
    borderColor: appColors.disabled,
  },
  consumedButtonText: {
    color: appColors.disabled,
    fontSize: 14,
    fontWeight: "600",
  },
  disabledButton: {
    opacity: 0.6,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: appColors.placeholder,
  },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
    paddingVertical: 64,
  },
  emptyStateTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: appColors.text,
    marginBottom: 8,
    textAlign: "center",
  },
  emptyStateText: {
    fontSize: 16,
    color: appColors.placeholder,
    textAlign: "center",
    lineHeight: 24,
  },
  errorState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
  },
  errorTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: appColors.error,
    marginBottom: 8,
    textAlign: "center",
  },
  errorText: {
    fontSize: 16,
    color: appColors.placeholder,
    textAlign: "center",
    lineHeight: 24,
    marginBottom: 24,
  },
  retryButton: {
    backgroundColor: appColors.primary,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  retryButtonText: {
    color: appColors.surface,
    fontSize: 16,
    fontWeight: "600",
  },
  filterContainer: {
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: appColors.surface,
    borderBottomWidth: 1,
    borderBottomColor: appColors.disabled + "20",
  },
  filterButton: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginHorizontal: 2,
    borderRadius: 16,
    backgroundColor: appColors.background,
    borderWidth: 1,
    borderColor: appColors.disabled + "40",
    alignItems: "center",
  },
  filterButtonActive: {
    backgroundColor: appColors.primary,
    borderColor: appColors.primary,
  },
  filterButtonText: {
    fontSize: 12,
    fontWeight: "600",
    color: appColors.placeholder,
    textAlign: "center",
  },
  filterButtonTextActive: {
    color: appColors.surface,
  },
});
