/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';

import type {
  MarketDto,
  MarketsDto
} from '.././model';


export const getCreateMarketResponseMock = (overrideResponse: Partial< MarketDto > = {}): MarketDto => ({updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, imageUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), id: faker.string.alpha(20), name: faker.string.alpha(20), address: faker.string.alpha(20), city: faker.string.alpha(20), state: faker.string.alpha(20), ...overrideResponse})

export const getReadMarketsResponseMock = (overrideResponse: Partial< MarketsDto > = {}): MarketsDto => ({records: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, imageUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), id: faker.string.alpha(20), name: faker.string.alpha(20), address: faker.string.alpha(20), city: faker.string.alpha(20), state: faker.string.alpha(20)})), count: faker.number.int({min: undefined, max: undefined}), total: faker.number.int({min: undefined, max: undefined}), nextOffset: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), null]), undefined]), ...overrideResponse})

export const getReadMarketResponseMock = (overrideResponse: Partial< MarketDto > = {}): MarketDto => ({updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, imageUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), id: faker.string.alpha(20), name: faker.string.alpha(20), address: faker.string.alpha(20), city: faker.string.alpha(20), state: faker.string.alpha(20), ...overrideResponse})

export const getUpdateMarketResponseMock = (overrideResponse: Partial< MarketDto > = {}): MarketDto => ({updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, imageUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), id: faker.string.alpha(20), name: faker.string.alpha(20), address: faker.string.alpha(20), city: faker.string.alpha(20), state: faker.string.alpha(20), ...overrideResponse})


export const getCreateMarketMockHandler = (overrideResponse?: MarketDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<MarketDto> | MarketDto)) => {
  return http.post('*/markets', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getCreateMarketResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getReadMarketsMockHandler = (overrideResponse?: MarketsDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MarketsDto> | MarketsDto)) => {
  return http.get('*/markets', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getReadMarketsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getReadMarketMockHandler = (overrideResponse?: MarketDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MarketDto> | MarketDto)) => {
  return http.get('*/markets/:marketId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getReadMarketResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getUpdateMarketMockHandler = (overrideResponse?: MarketDto | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<MarketDto> | MarketDto)) => {
  return http.patch('*/markets/:marketId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getUpdateMarketResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getDeleteMarketMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void)) => {
  return http.delete('*/markets/:marketId', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 204,
        
      })
  })
}
export const getMarketMock = () => [
  getCreateMarketMockHandler(),
  getReadMarketsMockHandler(),
  getReadMarketMockHandler(),
  getUpdateMarketMockHandler(),
  getDeleteMarketMockHandler()
]
